name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 5  # Increase the timeout as needed

    strategy:
        fail-fast: false  # Disable fast-fail
        matrix:
            PYTHON_VERSION: ['3.9', '3.10', '3.11', '3.12']  # I opted not to support Python 3.8 and below

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint pytest
        working-directory: .

      - name: Lint code
        run: |
          make lint
        working-directory: .

      - name: Run tests
        run: |
          pytest tests/
        working-directory: .
