name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 5  # Increase the timeout as needed

    strategy:
        fail-fast: false  # Disable fast-fail
        matrix:
            PYTHON_VERSION: ['3.9', '3.10', '3.11', '3.12']  # I opted not to support Python 3.8 and below

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.PYTHON_VERSION }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install commitlint
        run: |
          npm install
        working-directory: .

      - name: Validate commit messages
        run: |
          if [ $(git rev-list --count HEAD) -gt 1 ]; then \
            npx commitlint --from=HEAD~1 --to=HEAD \
          else \
            echo "No previous commit to compare against." \
          fi \
        working-directory: .

      - name: Install dependencies
        run: |
          make install
        working-directory: .

      - name: Lint code
        run: |
          make lint
        working-directory: .

      - name: Run tests
        run: |
          pytest tests/
        working-directory: .
